### ISSUE TITLE
Linker Error for AvidaRNG when compiling in Visual Studio

### ISSUE THREAD

**Issue by zairja** [devosoft/avida#13]
When compiling the source, I receive about 120 instances of the following error in Visual Studio:
```error LNK2001: unresolved external symbol "private: static int const Apto::RNG::AvidaRNG::MAX_SEED" (?MAX_SEED@AvidaRNG@RNG@Apto@@0HB)	C:\Users\z\Desktop\avidabin\avida-core\avida-core.lib(cAnalyzeJobWorker.obj)	avida```

I reproduced this issue in VS 2010, 2012 and 2013, all on Windows 7 with both CMake 3.0/3.1. I am not sure how to resolve it, but it appears that `apto/rng/AvidaRNG.h` from AvidaRNG.cc cannot be found. I checked to make sure the build order was correct and the proper dependencies were in place.

I was able to successfully compile on Windows in late 2014 though I no longer have access to that machine to compare configurations. Could anyone who has compiled it on Windows provide their setup and/or reproduce this issue?

**Comment by daonna** [comment]
I have met this issue yesterday and i don't konw how to do it?Can you give me some advice?Thank you.

**Comment by zairja** [comment]
@daonna At this time, Windows isn't really supported. You can either use an earlier version of Avida else use a supported OS (Mac/Linux).

**Comment by rholder613** [comment]
@zairja Really?  Windows isn't supported?  I've been getting a very similar error on Windows 8 using VS2014, but I've noticed there is both successful compiles of avida.exe and avida-ed.exe on Windows.  If "Windows isn't supported", how do we get these, exactly?

And surely, there's a fix for this error out there....somewhere.

In the meantime, I will try an earlier build of the source and see whether this error is repeated in earlier versions of the code....reporting back here if so.

**Comment by rholder613** [comment]
BTW - anyone reading this thread happen to have a quick answer as to what value is supposed to be assigned to the APTO_LIBRARY variable?  Is it .../lib/Debug/apto.lib or .../lib/Debug/apto.dll?

Tnx for the help!

**Comment by emilydolson** [comment]
@rholder613 Windows isn't supported right now, for the current version of Avida. There have indeed been versions in the past for which Windows was supported, but these don't have the most recent features, and we can't make any guarantees about them working on newer versions of Windows. Whether or not Windows is supported at any point in time tends to be determined by whether or not any of the current core developers use Windows. Right now, none of us do. We currently have some plans in the works that will result in more consistent cross-platform support, but it will be a while before they come to fruition. In the mean time, if you want to try to sift through the errors and get it running on Windows, more power to you!

**Comment by mercere99** [comment]
To echo Emily, we'd love to be able to have an active Windows release if any Windows developers wanted to put some time into getting it working.  All of the current developers volunteering time toward the project focus on either Linux or Mac.  It's been a long time since we've had anyone with real Windows expertise spending time on the project, so the compilation has never been pretty.
