### ISSUE TITLE
Unsuccessful cmake on master branch

### ISSUE THREAD

**Issue by colbrydi** [devosoft/avida#3]
I tried downloading a fresh copy of avida and install on our local HPC system.  However, the CMake command returned the following missing file error:

> cmake ..
> -- The C compiler identification is GNU
> -- The CXX compiler identification is GNU
> -- Check for working C compiler: /usr/bin/gcc
> -- Check for working C compiler: /usr/bin/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/g++
> -- Check for working CXX compiler: /usr/bin/g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> CMake Warning (dev) at CMakeLists.txt:19 (ADD_SUBDIRECTORY):
>   The source directory

```
/mnt/home/colbrydi/monitors/avida/libs/apto
```

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_FUSED_MADD
-- Performing Test HAVE_FUSED_MADD - Success
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
APTO_INCLUDE_DIR
   used as include directory in directory /mnt/home/colbrydi/monitors/avida/avida-core

-- Configuring incomplete, errors occurred!

**Comment by schmelling** [comment]
Hi,

I get the following error when running `git submodule update`

$ git submodule init

Submodule 'documentation' (https://github.com/devosoft/avida.wiki.git) registered for path 'documentation'
Submodule 'libs/apto' (git://programerror.com/apto.git) registered for path 'libs/apto'

$ git submodule update

Cloning into 'documentation'...
remote: Counting objects: 607, done.
remote: Total 607 (delta 0), reused 0 (delta 0), pack-reused 607
Receiving objects: 100% (607/607), 1.08 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (288/288), done.
Checking connectivity... done.
Submodule path 'documentation': checked out '50c9fb0973d9628e9b239e6abb7db827e1e6f9f8'
Cloning into 'libs/apto'...
fatal: unable to connect to programerror.com:
programerror.com[0: 173.230.148.102]: errno=Connection timed out

fatal: clone of 'git://programerror.com/apto.git' into submodule path 'libs/apto' failed

programerror.com seems up and running but the git://programerror.com/apto.git seems not to be working. Is there an easy work around via the original GitHub repo?

Cheers,
Nic

**Comment by ruppmatt** [comment]
Greetings-

I just did a fresh clone on my local machine and couldn't repeat the error.  There is a version of the apto library (Avida's equivalent of the STL) hosted on github.  If the problem persists, you can do the following:

In the avida directory edit the file .gitmodules to change the URL of the apto submodule to https://github.com/devosoft/apto.git (instead of its programerror URL)

Save and close the file.  Then run the command "git submodule sync" followed by "git submodule update".

That should change the remote origin of the submodule from programerror to github.

**Comment by schmelling** [comment]
thanks. worked for me.
