### ISSUE TITLE
Every time I use the Horizontal Gene Transfer I get segmentation fault, no matter what other variables I adjust?

### ISSUE THREAD

**Issue by rgvogel** [devosoft/avida#47]

**Comment by voidptr** [comment]
Would you please provide your configuration files?

**Comment by rgvogel** [comment]
Compiler: cmake 2.8.12.2

Platform: Red hat, Centos 7
 
./avida -s $seed 51 -set COPY_MUT_PROB .0008 -set WORLD_X 100 -set WORLD_Y 100 -set ENABLE_HGT 1 -set EVENT_FILE andEvents.cfg -def INST_SET instset-heads.cfg -set ENVIRONMENT_FILE environment.cfg

[Cfg.zip](https://github.com/devosoft/avida/files/1665583/Cfg.zip)

**Comment by voidptr** [comment]
I think there's a problem with your config files. Try mine, and see if they do better. You'll also want to compile using my latest source from the following repo and branch: https://github.com/voidptr/avida/tree/HGT_Master

The HGT implementation in the master Avida branch/repo is extremely old and buggy. 

Once you've got the code compiled, and the config files in place, you can run a simple HGT and changing environments experiment with:

./avida -v4 -set HGT_UPTAKE_RECOMBINATION_P 0.1 -set ENVIRONMENT_FILE environment__bonus0.cfg -set EVENT_FILE events_ce.cfg

**Comment by mmore500** [comment]
I added crash backtraces earlier this year, which should provide some better information to track down the source of the issue in case this occurs in the future. Closing the issue for now
