### ISSUE TITLE
Using local storage to store dish configurations and organisms

### ISSUE THREAD

**Issue by ninja542** [devosoft/avida#49]
I know you can download a zip file, but using local storage might be more convenient.

I would try to implement something myself, but I have no idea how the repo works, but there seems like there are no javascript files to edit?

Potentially an entire rewrite to html5 and javascript could be possible, if the C++ wrapper thing converts all the c++ code into canvas (unless I'm wrong?)

**Comment by mmore500** [comment]
I think you might be looking for the Avida-ED UI project, which you can find here <https://github.com/DBlackwood/AvidaED_user_interface>. Let me know if that's not the case.
