### ISSUE TITLE
Core dump while using resource dependent deme replication

### ISSUE THREAD

**Issue by aVeryStrangeLoop** [devosoft/avida#51]
While trying to program resource dependent deme replication (as in the documentation) I'm encountering the following error. 

```
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

The core dump only appears if I have the following line in the events.cfg file which is required for deme replication.

`u 1:1:end ReplicateDemes birth-count`

I'm guessing it's something to do with deleting objects while they are being used by the program.

**Comment by mmore500** [comment]
Hi Bhaskar :) 

I added backtrace support to the library earlier this year. I don't expect you're still running into this issue, but in case someone else has a similar problem there should at least be a line number reported that we can track down.
