### ISSUE TITLE
How to create random environmental fluctuations?

### ISSUE THREAD

**Issue by sturne29** [devosoft/avida#52]
I apologize if this isn't the correct forum for this, but I haven't been able to find anything about how to do something like this anywhere.

In the [maintenance of sex in changing environments](https://academic.oup.com/jhered/article/101/suppl_1/S46/760420) paper, the authors mention that they create a changing environment by randomly selecting a resource to change from a nutrient to a poison and a resource to change from a poison to a nutrient.

I would like to make a similarly fluctuating environment and wanted to know how those random changes were created. I assume it would be in the "Events" file, but I haven't been able to figure out how to create a code or script to randomly select the resources to change.

Thank you in advance! I'm very interested in the possibility of using this software.

**Comment by amlalejini** [comment]
I'm not sure if there's a way to have the environment change randomly without modifying Avida. 

When I needed randomly changing environments, I would use [insert scripting language of your choice, Python for me] to generate event files with the random environment changes. From Avida's perspective the environment was fully specified (in really long event files). The upside with this approach is that I could use my generated event files to know what the state of the environment was at every point during the run, which was useful for understanding evolved lineages.

**Comment by mercere99** [comment]
I'm almost positive that this is was Dule Misevic  did for the paper in question.  Generating your own environmental change file also lets you do a number of interesting controls, for example, using the exact same set of environmental changes, but with a different population (or random number seed) will allow you to disentangle the effect of a series of environmental states from other aspects of randomness affecting a run.

**Comment by sturne29** [comment]
Alright, thank you! That makes sense to me, and was actually similar to something I had thought of (but I wanted to know if there were a more straightforward way). This was very helpful, I appreciate the time both of you took to answer my question.

**Comment by emilydolson** [comment]
I agree that generating random files is probably the way to go, but just for future reference a couple of the environmental change events do support random changes (generally by supplying the keyword "RANDOM" in place of a resource name).

**Comment by sturne29** [comment]
That's also useful to know, thank you!
