### ISSUE TITLE
Unable to complete installation, Mac 10.14.5 

### ISSUE THREAD

**Issue by lorepieri8** [devosoft/avida#53]
After executing ` $ ./build_avida` I'm stuck at:

`[ 99%] Linking CXX executable ../bin/avida
[ 99%] Built target avida`

after approx. 1.5 hour. Should I wait more or something went wrong?
This is the content of the generated cbuild folder:

`CMakeCache.txt		Makefile		bin			lib
CMakeFiles		avida-core		cmake_install.cmake	libs`

which is missing a work folder.

**Comment by mmore500** [comment]
The build definitely shouldn't be taking half an hour :sweat_smile: 

We seem to have things working on a later version of mac (mac 11) in the CI. After you install the homebrew package manager, see here for a step by step on how to install requirements with homebrew <https://github.com/devosoft/avida/blob/3a38d1a0b6c62fbff2c940e20c7d90658e0c2a13/.github/workflows/ci.yaml#L41>

If you're still using an earlier version of the OS, feel free to reopen this issue.
