### ISSUE TITLE
git submodule update error

### ISSUE THREAD

**Issue by AC2020x** [devosoft/avida#54]
Help!  

On windows I am using git bash to clone avida.  After downloading the files, I use the submodules: init and update.  I get the following error message.  Please help!  If I use build the files using cmake and visual studio I run into tons of errors.  I believe it is due to this error.
Thanks!
Andrew

C:\Users\ac202\Desktop\avida>git submodule init
Submodule 'documentation' (https://github.com/devosoft/avida.wiki.git) registered for path 'documentation'
Submodule 'libs/apto' (https://github.com/dmbryson/apto.git) registered for path 'libs/apto'

C:\Users\ac202\Desktop\avida>git submodule update
Cloning into 'C:/Users/ac202/Desktop/avida/documentation'...
Cloning into 'C:/Users/ac202/Desktop/avida/libs/apto'...
error: invalid path 'Analyze-mode-:-building-your-own-commands.md'
Submodule path 'libs/apto': checked out '02e18980071d237f1ea4641f3f35cae469e2ed38'
Unable to checkout 'bc4f3557a748ba65697e9e681cd09f54dc4b1c97' in submodule path 'documentation'

**Comment by hreintke** [comment]
@AC2020x : 
I have the same issue. Did you find a solution for it ?

**Comment by mmore500** [comment]
Just fixed this a few months ago. Let me know if the current version clones ok for you!
